### ISSUE TITLE
TileSets

### ISSUE THREAD

**Issue by ay4me** [julian-upc/2015-algorithms#1]
So I would like to start a discussion about the TileSet definition.
As I see it a pentomino can be in a TileSet multiple times, exactly once per orientation it has.
But two pentominos that have same orientation but different coos, can those be both in one TileSet?

**Comment by julian-upc** [comment]
You have come across an issue that, sadly, happens too often in software projects: insufficient documentation and/or specification of the purpose of classes or functions.

The purpose of TileSet is to store one representative of each orientation of a pentomino, in normalized coordinates. That is to say, two translated copies should be merged into one, but a chiral pentomino and its reflected copy should be two different elements in the set.
