### ISSUE TITLE
normalize_coos()

### ISSUE THREAD

**Issue by ay4me** [julian-upc/2015-algorithms#2]
What exactly is this function supposed to do?
There is no testcase from which I could get ideas about this.

**Comment by julian-upc** [comment]
It's supposed to fix illegal coordinates that result from an operation such as flipping. See also https://github.com/julian-upc/2015-algorithms/issues/3#issuecomment-94704528

**Comment by ay4me** [comment]
Is it right, that up until now only negative coordinates are illegal?

**Comment by julian-upc** [comment]
Well, the point of a normalizing function is that it should be idempotent. So you should write a function that translates any pentomino to some nonnegative coordinates, but without having to know which pentomino you're actually normalizing, and such that applying your function twice gives the same result as applying it just once.

**Comment by TheUndertalker** [comment]
but this function has an input, coo. Should we only normalize coordinates corresponding to the direction specified by coo?

**Comment by julian-upc** [comment]
Actually, there are two functions:
```
    def normalize_coo(self, coo):
        pass

    def normalize(self):
        pass
```

**Comment by TheUndertalker** [comment]
Oh no I thought that this thread was about normalize_coo only my normalize resets flipping and rotation, too. Well I'm gonna fix this...

**Comment by TheUndertalker** [comment]
btw I see two idempotent ways to handle pentominos with positive coordinates: Moving them back to make them touch the axes or letting them stay where they are. Both are idempotent so it's still not exactly defined what we should do.
