### ISSUE TITLE
std::set problem

### ISSUE THREAD

**Issue by AndreG-P** [julian-upc/2015-algorithms#37]
It seems the function insert from std::set<Vector> uses the "<" operator to insert objects and prohibit multiple entries of the same object.
Is there another good container or solution to fix this?

**Comment by julian-upc** [comment]
That's actually exactly what ```set``` is for. I don't understand what precisely your problem is.

You can write a custom comparison operator for your class if you need that. Or, if you want to keep multiple copies of the same object, just ```push_back``` them into a ```std::vector```.
