### ISSUE TITLE
hashfunction

### ISSUE THREAD

**Issue by TheUndertalker** [julian-upc/2015-algorithms#4]
Ich bin mir nicht sicher, was __hash__(self) als Funktion genau ausgeben soll, nehme aber an, dass ein int erfordert wird. Stimmt das so?

**Comment by julian-upc** [comment]
Be aware that python has a built-in hash function:
https://docs.python.org/2/library/functions.html#hash

See also
https://docs.python.org/2/library/hashlib.html?highlight=hashlib#module-hashlib
