### ISSUE TITLE
turning around which point?

### ISSUE THREAD

**Issue by ay4me** [julian-upc/2015-algorithms#7]
The test wants I to have the same coordinates after turning it twice, that demands one specific turning point. 
If we normalize after turning anyway to get legal coordinates, why does it matter whether I moves when turned twice?

**Comment by ay4me** [comment]
So I know changed my turning method and the test still does not like it because the corrdinates are not in the same order as required.
This is, I think, really not necessary to ask for a specific order in the corrdinates.

**Comment by TheUndertalker** [comment]
I think so, too. The test should be changed, not your method.

**Comment by julian-upc** [comment]
I agree. That's what pull requests are for!
