### ISSUE TITLE
test for TileSet

### ISSUE THREAD

**Issue by ay4me** [julian-upc/2015-algorithms#8]
The test, that wants to check whether the 'Y' pentomino can be added in each orientation does not make deepcopies and therefore also rotates and flips the pentomino already in the set. Thereby the size o fthe set will always be 1.

**Comment by ay4me** [comment]
I resolved the problem, by making a deepcopy in the add() method of the TileSet.

**Comment by julian-upc** [comment]
Ok, so close the issue please!
